import Head from "next/head";

export default function Home() {
  const posts = [
    {
      title: "Post 1",
      content:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.",
    },
    {
      title: "Post 2",
      content:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.",
    },
  ];
  return (
    <div className="container mx-auto px-10 mb-2">
      <Head>
        <title>Blogyme</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
        <div className="lg:col-span-8 col-span-1">
          {posts.map((post) => (
            <div>
              <h1 className="text-2xl font-bold">{post.title}</h1>
              <p className="text-gray-500">{post.content}</p>
            </div>
          ))}
        </div>
        <div className="lg:col-span-4 col-span-1">
          <div className="lg:sticky  relative top-8">
            
          </div>
        </div>
      </div>
    </div>
  );
}
